In [4]:

import pandas as pd
import numpy as np

In [5]:

credits = pd.read_csv("/content/credits.csv", low_memory=False)
keywords = pd.read_csv("/content/keywords.csv", low_memory=False)
ratings = pd.read_csv("/content/ratings.csv", low_memory=False)
movies = pd.read_csv("/content/movies_metadata.csv", low_memory=False)

In [6]:

print("Credits:", credits.shape)
print("Keywords:", keywords.shape)
print("Ratings:", ratings.shape)
print("Movies:", movies.shape)

Credits: (45476, 3)
Keywords: (46419, 2)
Ratings: (26024289, 4)
Movies: (45466, 24)

In [7]:

display(movies.head())
display(credits.head())
display(keywords.head())
display(ratings.head())

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [8]:

for name, df in {
    "Movies": movies,
    "Credits": credits,
    "Keywords": keywords,
    "Ratings": ratings
}.items():
    print(f"\n{name}")
    print(df.info())

Movies
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB
None

Credits
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45476 non-null  object
 1   crew    45476 non-null  object
 2   id      45476 non-null  int64
dtypes: int64(1), object(2)
memory usage: 1.0+ MB
None

Keywords
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46419 entries, 0 to 46418
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        46419 non-null  int64
 1   keywords  46419 non-null  object
dtypes: int64(1), object(1)
memory usage: 725.4+ KB
None

Ratings
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26024289 entries, 0 to 26024288
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  int64
dtypes: float64(1), int64(3)
memory usage: 794.2 MB
None

In [9]:

datasets = {
    "movies": movies,
    "credits": credits,
    "keywords": keywords,
    "ratings": ratings
}

for name, df in datasets.items():
    print(f"\n{'='*30}")
    print(name.upper())
    print("Missing values:")
    print(df.isnull().sum().sort_values(ascending=False).head(15))
    print("Duplicate rows:", df.duplicated().sum())

==============================
MOVIES
Missing values:
belongs_to_collection    40972
homepage                 37684
tagline                  25054
overview                   954
poster_path                386
runtime                    263
status                      87
release_date                87
imdb_id                     17
original_language           11
vote_average                 6
vote_count                   6
title                        6
video                        6
spoken_languages             6
dtype: int64
Duplicate rows: 17

==============================
CREDITS
Missing values:
cast    0
crew    0
id      0
dtype: int64
Duplicate rows: 37

==============================
KEYWORDS
Missing values:
id          0
keywords    0
dtype: int64
Duplicate rows: 987

==============================
RATINGS
Missing values:
userId       0
movieId      0
rating       0
timestamp    0
dtype: int64
Duplicate rows: 0

In [10]:
movies_clean = movies.copy()

In [11]:
movies_clean.columns.tolist()

['adult',
 'belongs_to_collection',
 'budget',
 'genres',
 'homepage',
 'id',
 'imdb_id',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'poster_path',
 'production_companies',
 'production_countries',
 'release_date',
 'revenue',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'video',
 'vote_average',
 'vote_count']

In [12]:
import pandas as pd
import numpy as np

movies = pd.read_csv("/content/movies_metadata.csv", low_memory=False)
credits = pd.read_csv("/content/credits.csv", low_memory=False)
keywords = pd.read_csv("/content/keywords.csv", low_memory=False)
ratings = pd.read_csv("/content/ratings.csv", low_memory=False)

In [13]:
movies_clean = movies.copy()

In [14]:
movies_clean.columns.tolist()

['adult',
 'belongs_to_collection',
 'budget',
 'genres',
 'homepage',
 'id',
 'imdb_id',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'poster_path',
 'production_companies',
 'production_countries',
 'release_date',
 'revenue',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'video',
 'vote_average',
 'vote_count']

In [15]:
movies_clean.columns.tolist()

['adult',
 'belongs_to_collection',
 'budget',
 'genres',
 'homepage',
 'id',
 'imdb_id',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'poster_path',
 'production_companies',
 'production_countries',
 'release_date',
 'revenue',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'video',
 'vote_average',
 'vote_count']

In [16]:
movies_clean = movies.copy()

In [17]:
movies_clean[['id', 'title', 'genres', 'overview', 'vote_average', 'vote_count']].head()

,id,title,genres,overview,vote_average,vote_count
0,862,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",7.7,5415.0
1,8844,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,6.9,2413.0
2,15602,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,6.5,92.0
3,31357,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",6.1,34.0
4,11862,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,5.7,173.0

In [18]:
movies_clean[['id', 'title', 'genres', 'overview', 'vote_average', 'vote_count']].isnull().sum()

id                0
title             6
genres            0
overview        954
vote_average      6
vote_count        6
dtype: int64

In [19]:
movies_clean[['id', 'title', 'genres', 'overview', 'vote_average', 'vote_count']].isnull().sum()

id                0
title             6
genres            0
overview        954
vote_average      6
vote_count        6
dtype: int64

In [20]:
movies_clean = movies_clean.dropna(subset=['title']).copy()

In [21]:
movies_clean['overview'] = movies_clean['overview'].fillna('')

In [22]:
movies_clean = movies_clean.dropna(subset=['title']).copy()

movies_clean['overview'] = movies_clean['overview'].fillna('')

In [23]:
movies_clean[['id', 'title', 'genres', 'overview',
              'vote_average', 'vote_count']].isnull().sum()

id              0
title           0
genres          0
overview        0
vote_average    0
vote_count      0
dtype: int64

In [24]:
movies_clean['genres'].head(5)

0    [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1    [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2    [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3    [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                       [{'id': 35, 'name': 'Comedy'}]
Name: genres, dtype: object

In [25]:
[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'}]

[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}]

In [26]:
import ast

def parse_genres(x):
    try:
        return ast.literal_eval(x) if isinstance(x, str) else []
    except (ValueError, SyntaxError):
        return []

movies_clean['genres_parsed'] = movies_clean['genres'].apply(parse_genres)

In [27]:
def get_genre_names(genre_list):
    if not isinstance(genre_list, list):
        return []
    return [
        genre['name']
        for genre in genre_list
        if isinstance(genre, dict) and genre.get('name')
    ]

movies_clean['genres_clean'] = movies_clean['genres_parsed'].apply(get_genre_names)

In [28]:
movies_clean['genres_text'] = movies_clean['genres_clean'].apply(
    lambda x: ' '.join(x)
)

In [29]:
movies_clean[['title', 'genres', 'genres_text']].head(10)

,title,genres,genres_text
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",Animation Comedy Family
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Adventure Fantasy Family
2,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Romance Comedy
3,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Comedy Drama Romance
4,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Comedy
5,Heat,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",Action Crime Drama Thriller
6,Sabrina,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",Comedy Romance
7,Tom and Huck,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Drama Family
8,Sudden Death,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Thriller
9,GoldenEye,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",Adventure Action Thriller

In [30]:
credits_clean = credits.copy()

In [31]:
credits_clean.columns.tolist()

['cast', 'crew', 'id']

In [32]:
credits_clean.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [33]:
credits_clean.columns.tolist()

['cast', 'crew', 'id']

In [34]:
credits_clean = credits.copy()

In [35]:
credits_clean.columns.tolist()

['cast', 'crew', 'id']

In [36]:
credits_clean.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [37]:
print(credits_clean['cast'].iloc[0])

[{'cast_id': 14, 'character': 'Woody (voice)', 'credit_id': '52fe4284c3a36847f8024f95', 'gender': 2, 'id': 31, 'name': 'Tom Hanks', 'order': 0, 'profile_path': '/pQFoyx7rp09CJTAb932F2g8Nlho.jpg'}, {'cast_id': 15, 'character': 'Buzz Lightyear (voice)', 'credit_id': '52fe4284c3a36847f8024f99', 'gender': 2, 'id': 12898, 'name': 'Tim Allen', 'order': 1, 'profile_path': '/uX2xVf6pMmPepxnvFWyBtjexzgY.jpg'}, {'cast_id': 16, 'character': 'Mr. Potato Head (voice)', 'credit_id': '52fe4284c3a36847f8024f9d', 'gender': 2, 'id': 7167, 'name': 'Don Rickles', 'order': 2, 'profile_path': '/h5BcaDMPRVLHLDzbQavec4xfSdt.jpg'}, {'cast_id': 17, 'character': 'Slinky Dog (voice)', 'credit_id': '52fe4284c3a36847f8024fa1', 'gender': 2, 'id': 12899, 'name': 'Jim Varney', 'order': 3, 'profile_path': '/eIo2jVVXYgjDtaHoF19Ll9vtW7h.jpg'}, {'cast_id': 18, 'character': 'Rex (voice)', 'credit_id': '52fe4284c3a36847f8024fa5', 'gender': 2, 'id': 12900, 'name': 'Wallace Shawn', 'order': 4, 'profile_path': '/oGE6JqPP2xH4tNORKNqxbNPYi7u.jpg'}, {'cast_id': 19, 'character': 'Hamm (voice)', 'credit_id': '52fe4284c3a36847f8024fa9', 'gender': 2, 'id': 7907, 'name': 'John Ratzenberger', 'order': 5, 'profile_path': '/yGechiKWL6TJDfVE2KPSJYqdMsY.jpg'}, {'cast_id': 20, 'character': 'Bo Peep (voice)', 'credit_id': '52fe4284c3a36847f8024fad', 'gender': 1, 'id': 8873, 'name': 'Annie Potts', 'order': 6, 'profile_path': '/eryXT84RL41jHSJcMy4kS3u9y6w.jpg'}, {'cast_id': 26, 'character': 'Andy (voice)', 'credit_id': '52fe4284c3a36847f8024fc1', 'gender': 0, 'id': 1116442, 'name': 'John Morris', 'order': 7, 'profile_path': '/vYGyvK4LzeaUCoNSHtsuqJUY15M.jpg'}, {'cast_id': 22, 'character': 'Sid (voice)', 'credit_id': '52fe4284c3a36847f8024fb1', 'gender': 2, 'id': 12901, 'name': 'Erik von Detten', 'order': 8, 'profile_path': '/twnF1ZaJ1FUNUuo6xLXwcxjayBE.jpg'}, {'cast_id': 23, 'character': 'Mrs. Davis (voice)', 'credit_id': '52fe4284c3a36847f8024fb5', 'gender': 1, 'id': 12133, 'name': 'Laurie Metcalf', 'order': 9, 'profile_path': '/unMMIT60eoBM2sN2nyR7EZ2BvvD.jpg'}, {'cast_id': 24, 'character': 'Sergeant (voice)', 'credit_id': '52fe4284c3a36847f8024fb9', 'gender': 2, 'id': 8655, 'name': 'R. Lee Ermey', 'order': 10, 'profile_path': '/r8GBqFBjypLUP9VVqDqfZ7wYbSs.jpg'}, {'cast_id': 25, 'character': 'Hannah (voice)', 'credit_id': '52fe4284c3a36847f8024fbd', 'gender': 1, 'id': 12903, 'name': 'Sarah Freeman', 'order': 11, 'profile_path': None}, {'cast_id': 27, 'character': 'TV Announcer (voice)', 'credit_id': '52fe4284c3a36847f8024fc5', 'gender': 2, 'id': 37221, 'name': 'Penn Jillette', 'order': 12, 'profile_path': '/zmAaXUdx12NRsssgHbk1T31j2x9.jpg'}]

In [38]:
print(credits_clean['crew'].iloc[0])

[{'credit_id': '52fe4284c3a36847f8024f49', 'department': 'Directing', 'gender': 2, 'id': 7879, 'job': 'Director', 'name': 'John Lasseter', 'profile_path': '/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg'}, {'credit_id': '52fe4284c3a36847f8024f4f', 'department': 'Writing', 'gender': 2, 'id': 12891, 'job': 'Screenplay', 'name': 'Joss Whedon', 'profile_path': '/dTiVsuaTVTeGmvkhcyJvKp2A5kr.jpg'}, {'credit_id': '52fe4284c3a36847f8024f55', 'department': 'Writing', 'gender': 2, 'id': 7, 'job': 'Screenplay', 'name': 'Andrew Stanton', 'profile_path': '/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg'}, {'credit_id': '52fe4284c3a36847f8024f5b', 'department': 'Writing', 'gender': 2, 'id': 12892, 'job': 'Screenplay', 'name': 'Joel Cohen', 'profile_path': '/dAubAiZcvKFbboWlj7oXOkZnTSu.jpg'}, {'credit_id': '52fe4284c3a36847f8024f61', 'department': 'Writing', 'gender': 0, 'id': 12893, 'job': 'Screenplay', 'name': 'Alec Sokolow', 'profile_path': '/v79vlRYi94BZUQnkkyznbGUZLjT.jpg'}, {'credit_id': '52fe4284c3a36847f8024f67', 'department': 'Production', 'gender': 1, 'id': 12894, 'job': 'Producer', 'name': 'Bonnie Arnold', 'profile_path': None}, {'credit_id': '52fe4284c3a36847f8024f6d', 'department': 'Production', 'gender': 0, 'id': 12895, 'job': 'Executive Producer', 'name': 'Ed Catmull', 'profile_path': None}, {'credit_id': '52fe4284c3a36847f8024f73', 'department': 'Production', 'gender': 2, 'id': 12896, 'job': 'Producer', 'name': 'Ralph Guggenheim', 'profile_path': None}, {'credit_id': '52fe4284c3a36847f8024f79', 'department': 'Production', 'gender': 2, 'id': 12897, 'job': 'Executive Producer', 'name': 'Steve Jobs', 'profile_path': '/mOMP3SwD5qWQSR0ldCIByd3guTV.jpg'}, {'credit_id': '52fe4284c3a36847f8024f8b', 'department': 'Editing', 'gender': 2, 'id': 8, 'job': 'Editor', 'name': 'Lee Unkrich', 'profile_path': '/bdTCCXjgOV3YyaNmLGYGOxFQMOc.jpg'}, {'credit_id': '52fe4284c3a36847f8024f91', 'department': 'Art', 'gender': 2, 'id': 7883, 'job': 'Art Direction', 'name': 'Ralph Eggleston', 'profile_path': '/uUfcGKDsKO1aROMpXRs67Hn6RvR.jpg'}, {'credit_id': '598331bf925141421201044b', 'department': 'Editing', 'gender': 2, 'id': 1168870, 'job': 'Editor', 'name': 'Robert Gordon', 'profile_path': None}, {'credit_id': '5892168cc3a36809660095f9', 'department': 'Sound', 'gender': 0, 'id': 1552883, 'job': 'Foley Editor', 'name': 'Mary Helen Leasman', 'profile_path': None}, {'credit_id': '5531824d9251415289000945', 'department': 'Visual Effects', 'gender': 0, 'id': 1453514, 'job': 'Animation', 'name': 'Kim Blanchette', 'profile_path': None}, {'credit_id': '589215969251412dcb009bf6', 'department': 'Sound', 'gender': 0, 'id': 1414182, 'job': 'ADR Editor', 'name': 'Marilyn McCoppen', 'profile_path': None}, {'credit_id': '589217099251412dc500a018', 'department': 'Sound', 'gender': 2, 'id': 7885, 'job': 'Orchestrator', 'name': 'Randy Newman', 'profile_path': '/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg'}, {'credit_id': '5693e6b29251417b0e0000e3', 'department': 'Editing', 'gender': 0, 'id': 1429549, 'job': 'Color Timer', 'name': 'Dale E. Grahn', 'profile_path': None}, {'credit_id': '572e2522c3a36869e6001a9c', 'department': 'Visual Effects', 'gender': 0, 'id': 7949, 'job': 'CG Painter', 'name': 'Robin Cooper', 'profile_path': None}, {'credit_id': '574f12309251415ca1000012', 'department': 'Writing', 'gender': 2, 'id': 7879, 'job': 'Original Story', 'name': 'John Lasseter', 'profile_path': '/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg'}, {'credit_id': '574f1240c3a3682e7300001c', 'department': 'Writing', 'gender': 2, 'id': 12890, 'job': 'Original Story', 'name': 'Pete Docter', 'profile_path': '/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg'}, {'credit_id': '574f12519251415c92000015', 'department': 'Writing', 'gender': 0, 'id': 7911, 'job': 'Original Story', 'name': 'Joe Ranft', 'profile_path': '/f1BoWC2JbCcfP1e5hKfGsxkHzVU.jpg'}, {'credit_id': '574f12cec3a3682e82000022', 'department': 'Crew', 'gender': 0, 'id': 1629419, 'job': 'Post Production Supervisor', 'name': 'Patsy Bouge', 'profile_path': None}, {'credit_id': '574f14f19251415ca1000082', 'department': 'Art', 'gender': 0, 'id': 7961, 'job': 'Sculptor', 'name': 'Norm DeCarlo', 'profile_path': None}, {'credit_id': '5751ae4bc3a3683772002b7f', 'department': 'Visual Effects', 'gender': 2, 'id': 12905, 'job': 'Animation Director', 'name': 'Ash Brannon', 'profile_path': '/6ueWgPEEBHvS3De2BHYQnYjRTig.jpg'}, {'credit_id': '5891edbe9251412dc5007cd6', 'department': 'Sound', 'gender': 2, 'id': 7885, 'job': 'Music', 'name': 'Randy Newman', 'profile_path': '/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg'}, {'credit_id': '589213d39251412dc8009832', 'department': 'Directing', 'gender': 0, 'id': 1748707, 'job': 'Layout', 'name': 'Roman Figun', 'profile_path': None}, {'credit_id': '5892173dc3a3680968009351', 'department': 'Sound', 'gender': 2, 'id': 4949, 'job': 'Orchestrator', 'name': 'Don Davis', 'profile_path': None}, {'credit_id': '589217cec3a3686b0a0052ba', 'department': 'Sound', 'gender': 0, 'id': 1372885, 'job': 'Music Editor', 'name': 'James Flamberg', 'profile_path': None}, {'credit_id': '58921831c3a3686348004a64', 'department': 'Editing', 'gender': 0, 'id': 1739962, 'job': 'Negative Cutter', 'name': 'Mary Beth Smith', 'profile_path': None}, {'credit_id': '58921838c3a36809700096c0', 'department': 'Editing', 'gender': 0, 'id': 1748513, 'job': 'Negative Cutter', 'name': 'Rick Mackay', 'profile_path': None}, {'credit_id': '589218429251412dd1009d1b', 'department': 'Art', 'gender': 0, 'id': 1458006, 'job': 'Title Designer', 'name': 'Susan Bradley', 'profile_path': None}, {'credit_id': '5891ed99c3a3680966007670', 'department': 'Crew', 'gender': 0, 'id': 1748557, 'job': 'Supervising Technical Director', 'name': 'William Reeves', 'profile_path': None}, {'credit_id': '5891edcec3a3686b0a002eb2', 'department': 'Sound', 'gender': 2, 'id': 7885, 'job': 'Songs', 'name': 'Randy Newman', 'profile_path': '/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg'}, {'credit_id': '5891edf9c3a36809700075e6', 'department': 'Writing', 'gender': 2, 'id': 7, 'job': 'Original Story', 'name': 'Andrew Stanton', 'profile_path': '/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg'}, {'credit_id': '58920f0b9251412dd7009104', 'department': 'Crew', 'gender': 2, 'id': 12890, 'job': 'Supervising Animator', 'name': 'Pete Docter', 'profile_path': '/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg'}, {'credit_id': '58920f1fc3a3680977009021', 'department': 'Sound', 'gender': 2, 'id': 2216, 'job': 'Sound Designer', 'name': 'Gary Rydstrom', 'profile_path': '/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg'}, {'credit_id': '58920f389251412dd700912d', 'department': 'Production', 'gender': 0, 'id': 12909, 'job': 'Production Supervisor', 'name': 'Karen Robert Jackson', 'profile_path': None}, {'credit_id': '58920fbd9251412dcb00969c', 'department': 'Crew', 'gender': 0, 'id': 953331, 'job': 'Executive Music Producer', 'name': 'Chris Montan', 'profile_path': None}, {'credit_id': '589210069251412dd7009219', 'department': 'Visual Effects', 'gender': 0, 'id': 7893, 'job': 'Animation Director', 'name': 'Rich Quade', 'profile_path': None}, {'credit_id': '589210329251412dcd00943b', 'department': 'Visual Effects', 'gender': 0, 'id': 8025, 'job': 'Animation', 'name': 'Michael Berenstein', 'profile_path': None}, {'credit_id': '5892103bc3a368096a009180', 'department': 'Visual Effects', 'gender': 0, 'id': 78009, 'job': 'Animation', 'name': 'Colin Brady', 'profile_path': None}, {'credit_id': '5892105dc3a3680968008db2', 'department': 'Visual Effects', 'gender': 0, 'id': 1748682, 'job': 'Animation', 'name': 'Davey Crockett Feiten', 'profile_path': None}, {'credit_id': '589210669251412dcd009466', 'department': 'Visual Effects', 'gender': 0, 'id': 1454030, 'job': 'Animation', 'name': 'Angie Glocka', 'profile_path': None}, {'credit_id': '5892107c9251412dd1009613', 'department': 'Visual Effects', 'gender': 0, 'id': 1748683, 'job': 'Animation', 'name': 'Rex Grignon', 'profile_path': None}, {'credit_id': '5892108ac3a3680973008d3f', 'department': 'Visual Effects', 'gender': 0, 'id': 1748684, 'job': 'Animation', 'name': 'Tom K. Gurney', 'profile_path': None}, {'credit_id': '58921093c3a3686348004477', 'department': 'Visual Effects', 'gender': 2, 'id': 8029, 'job': 'Animation', 'name': 'Jimmy Hayward', 'profile_path': '/lTDRpudEY7BDwTefXbXzMlmb0ui.jpg'}, {'credit_id': '5892109b9251412dcd0094b0', 'department': 'Visual Effects', 'gender': 0, 'id': 1426773, 'job': 'Animation', 'name': 'Hal T. Hickel', 'profile_path': None}, {'credit_id': '589210a29251412dc5009a29', 'department': 'Visual Effects', 'gender': 0, 'id': 8035, 'job': 'Animation', 'name': 'Karen Kiser', 'profile_path': None}, {'credit_id': '589210ccc3a3680977009191', 'department': 'Visual Effects', 'gender': 0, 'id': 1748688, 'job': 'Animation', 'name': 'Anthony B. LaMolinara', 'profile_path': None}, {'credit_id': '589210d7c3a3686b0a004c1f', 'department': 'Visual Effects', 'gender': 0, 'id': 587314, 'job': 'Animation', 'name': 'Guionne Leroy', 'profile_path': None}, {'credit_id': '589210e1c3a36809770091a7', 'department': 'Visual Effects', 'gender': 2, 'id': 7918, 'job': 'Animation', 'name': 'Bud Luckey', 'profile_path': '/pcCh7G19FKMNijmPQg1PMH1btic.jpg'}, {'credit_id': '589210ee9251412dc200978a', 'department': 'Visual Effects', 'gender': 0, 'id': 1748689, 'job': 'Animation', 'name': 'Les Major', 'profile_path': None}, {'credit_id': '589210fa9251412dc8009595', 'department': 'Visual Effects', 'gender': 2, 'id': 7892, 'job': 'Animation', 'name': 'Glenn McQueen', 'profile_path': None}, {'credit_id': '589211029251412dc8009598', 'department': 'Visual Effects', 'gender': 0, 'id': 555795, 'job': 'Animation', 'name': 'Mark Oftedal', 'profile_path': None}, {'credit_id': '5892110b9251412dc800959d', 'department': 'Visual Effects', 'gender': 2, 'id': 7882, 'job': 'Animation', 'name': 'Jeff Pidgeon', 'profile_path': '/yLddkg5HcgbJg00cS13GVBnP0HY.jpg'}, {'credit_id': '58921113c3a36863480044e4', 'department': 'Visual Effects', 'gender': 0, 'id': 8017, 'job': 'Animation', 'name': 'Jeff Pratt', 'profile_path': None}, {'credit_id': '5892111c9251412dcb0097e9', 'department': 'Visual Effects', 'gender': 0, 'id': 1184140, 'job': 'Animation', 'name': 'Steve Rabatich', 'profile_path': None}, {'credit_id': '58921123c3a36809700090f6', 'department': 'Visual Effects', 'gender': 0, 'id': 8049, 'job': 'Animation', 'name': 'Roger Rose', 'profile_path': None}, {'credit_id': '5892112b9251412dcb0097fb', 'department': 'Visual Effects', 'gender': 0, 'id': 1509559, 'job': 'Animation', 'name': 'Steve Segal', 'profile_path': None}, {'credit_id': '589211349251412dc80095c3', 'department': 'Visual Effects', 'gender': 0, 'id': 1748691, 'job': 'Animation', 'name': 'Doug Sheppeck', 'profile_path': None}, {'credit_id': '5892113cc3a3680970009106', 'department': 'Visual Effects', 'gender': 0, 'id': 8050, 'job': 'Animation', 'name': 'Alan Sperling', 'profile_path': None}, {'credit_id': '58921148c3a3686b0a004c99', 'department': 'Visual Effects', 'gender': 0, 'id': 8010, 'job': 'Animation', 'name': 'Doug Sweetland', 'profile_path': None}, {'credit_id': '58921150c3a3680966009125', 'department': 'Visual Effects', 'gender': 0, 'id': 8044, 'job': 'Animation', 'name': 'David Tart', 'profile_path': None}, {'credit_id': '589211629251412dc5009b00', 'department': 'Visual Effects', 'gender': 0, 'id': 1454034, 'job': 'Animation', 'name': 'Ken Willard', 'profile_path': None}, {'credit_id': '589211c1c3a3686b0a004d28', 'department': 'Visual Effects', 'gender': 0, 'id': 7887, 'job': 'Visual Effects Supervisor', 'name': 'Thomas Porter', 'profile_path': None}, {'credit_id': '589211d4c3a3680968008ed9', 'department': 'Visual Effects', 'gender': 0, 'id': 1406878, 'job': 'Visual Effects', 'name': 'Mark Thomas Henne', 'profile_path': None}, {'credit_id': '589211f59251412dd4008e65', 'department': 'Visual Effects', 'gender': 0, 'id': 1748698, 'job': 'Visual Effects', 'name': 'Oren Jacob', 'profile_path': None}, {'credit_id': '58921242c3a368096a00939b', 'department': 'Visual Effects', 'gender': 0, 'id': 1748699, 'job': 'Visual Effects', 'name': 'Darwyn Peachey', 'profile_path': None}, {'credit_id': '5892124b9251412dc5009bd2', 'department': 'Visual Effects', 'gender': 0, 'id': 1748701, 'job': 'Visual Effects', 'name': 'Mitch Prater', 'profile_path': None}, {'credit_id': '58921264c3a3686b0a004dbf', 'department': 'Visual Effects', 'gender': 0, 'id': 1748703, 'job': 'Visual Effects', 'name': 'Brian M. Rosen', 'profile_path': None}, {'credit_id': '589212709251412dcd009676', 'department': 'Lighting', 'gender': 1, 'id': 12912, 'job': 'Lighting Supervisor', 'name': 'Sharon Calahan', 'profile_path': None}, {'credit_id': '5892127fc3a3686b0a004de5', 'department': 'Lighting', 'gender': 0, 'id': 7899, 'job': 'Lighting Supervisor', 'name': 'Galyn Susman', 'profile_path': None}, {'credit_id': '589212cdc3a3680970009268', 'department': 'Visual Effects', 'gender': 0, 'id': 12915, 'job': 'CG Painter', 'name': 'William Cone', 'profile_path': None}, {'credit_id': '5892130f9251412dc8009791', 'department': 'Art', 'gender': 0, 'id': 1748705, 'job': 'Sculptor', 'name': 'Shelley Daniels Lekven', 'profile_path': None}, {'credit_id': '5892131c9251412dd4008f4c', 'department': 'Visual Effects', 'gender': 2, 'id': 7889, 'job': 'Character Designer', 'name': 'Bob Pauley', 'profile_path': None}, {'credit_id': '589213249251412dd100987b', 'department': 'Visual Effects', 'gender': 2, 'id': 7918, 'job': 'Character Designer', 'name': 'Bud Luckey', 'profile_path': '/pcCh7G19FKMNijmPQg1PMH1btic.jpg'}, {'credit_id': '5892132b9251412dc80097b1', 'department': 'Visual Effects', 'gender': 2, 'id': 7, 'job': 'Character Designer', 'name': 'Andrew Stanton', 'profile_path': '/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg'}, {'credit_id': '58921332c3a368634800467b', 'department': 'Visual Effects', 'gender': 0, 'id': 12915, 'job': 'Character Designer', 'name': 'William Cone', 'profile_path': None}, {'credit_id': '5892135f9251412dd4008f90', 'department': 'Visual Effects', 'gender': 0, 'id': 1748706, 'job': 'Character Designer', 'name': 'Steve Johnson', 'profile_path': None}, {'credit_id': '58921384c3a3680973008fd4', 'department': 'Visual Effects', 'gender': 0, 'id': 1176752, 'job': 'Character Designer', 'name': 'Dan Haskett', 'profile_path': None}, {'credit_id': '5892138e9251412dc20099fc', 'department': 'Visual Effects', 'gender': 0, 'id': 1088034, 'job': 'Character Designer', 'name': 'Tom Holloway', 'profile_path': '/a0r0T2usTBpgMI5aZbRBDW1fTl8.jpg'}, {'credit_id': '58921395c3a368097700942f', 'department': 'Visual Effects', 'gender': 0, 'id': 1447465, 'job': 'Character Designer', 'name': 'Jean Gillmore', 'profile_path': None}, {'credit_id': '589213e2c3a3680973009026', 'department': 'Directing', 'gender': 0, 'id': 1748709, 'job': 'Layout', 'name': 'Desirée Mourad', 'profile_path': None}, {'credit_id': '589214099251412dc5009d57', 'department': 'Art', 'gender': 0, 'id': 1748710, 'job': 'Set Dresser', 'name': "Kelly O'Connell", 'profile_path': None}, {'credit_id': '58921411c3a3686b0a004f70', 'department': 'Art', 'gender': 0, 'id': 1443471, 'job': 'Set Dresser', 'name': 'Sonoko Konishi', 'profile_path': None}, {'credit_id': '58921434c3a368096a00956e', 'department': 'Art', 'gender': 0, 'id': 1748711, 'job': 'Set Dresser', 'name': 'Ann M. Rockwell', 'profile_path': None}, {'credit_id': '5892144ac3a36809680090de', 'department': 'Editing', 'gender': 0, 'id': 1748712, 'job': 'Editorial Manager', 'name': 'Julie M. McDonald', 'profile_path': None}, {'credit_id': '58921479c3a368096800910f', 'department': 'Editing', 'gender': 0, 'id': 1589729, 'job': 'Assistant Editor', 'name': 'Robin Lee', 'profile_path': None}, {'credit_id': '5892148b9251412dd10099cc', 'department': 'Editing', 'gender': 0, 'id': 1748716, 'job': 'Assistant Editor', 'name': 'Tom Freeman', 'profile_path': None}, {'credit_id': '589214959251412dcb009b1f', 'department': 'Editing', 'gender': 0, 'id': 1748717, 'job': 'Assistant Editor', 'name': 'Ada Cochavi', 'profile_path': None}, {'credit_id': '5892149ec3a3686348004798', 'department': 'Editing', 'gender': 0, 'id': 1336438, 'job': 'Assistant Editor', 'name': 'Dana Mulligan', 'profile_path': None}, {'credit_id': '589214adc3a368096a0095db', 'department': 'Editing', 'gender': 0, 'id': 1748718, 'job': 'Editorial Coordinator', 'name': 'Deirdre Morrison', 'profile_path': None}, {'credit_id': '589214c7c3a368097700952b', 'department': 'Production', 'gender': 0, 'id': 1748719, 'job': 'Production Coordinator', 'name': 'Lori Lombardo', 'profile_path': None}, {'credit_id': '589214cec3a368096a009603', 'department': 'Production', 'gender': 0, 'id': 1748720, 'job': 'Production Coordinator', 'name': 'Ellen Devine', 'profile_path': None}, {'credit_id': '589214e39251412dc8009904', 'department': 'Crew', 'gender': 0, 'id': 1468014, 'job': 'Unit Publicist', 'name': 'Lauren Beth Strogoff', 'profile_path': None}, {'credit_id': '58921544c3a3686b0a00507d', 'department': 'Sound', 'gender': 2, 'id': 2216, 'job': 'Sound Re-Recording Mixer', 'name': 'Gary Rydstrom', 'profile_path': '/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg'}, {'credit_id': '5892154c9251412dd1009a56', 'department': 'Sound', 'gender': 0, 'id': 1425978, 'job': 'Sound Re-Recording Mixer', 'name': 'Gary Summers', 'profile_path': None}, {'credit_id': '58921555c3a36809680091bd', 'department': 'Sound', 'gender': 2, 'id': 8276, 'job': 'Supervising Sound Editor', 'name': 'Tim Holland', 'profile_path': None}, {'credit_id': '589215c39251412dcb009c12', 'department': 'Sound', 'gender': 0, 'id': 7069, 'job': 'Sound Effects Editor', 'name': 'Pat Jackson', 'profile_path': None}, {'credit_id': '58921698c3a368096a009788', 'department': 'Crew', 'gender': 2, 'id': 15894, 'job': 'Sound Design Assistant', 'name': 'Tom Myers', 'profile_path': None}, {'credit_id': '589216a89251412dc2009ca4', 'department': 'Sound', 'gender': 0, 'id': 1414177, 'job': 'Assistant Sound Editor', 'name': 'J.R. Grubbs', 'profile_path': None}, {'credit_id': '589216c19251412dc2009cb9', 'department': 'Sound', 'gender': 1, 'id': 1748724, 'job': 'Assistant Sound Editor', 'name': 'Susan Sanford', 'profile_path': None}, {'credit_id': '589216ccc3a3680973009274', 'department': 'Sound', 'gender': 0, 'id': 1748725, 'job': 'Assistant Sound Editor', 'name': 'Susan Popovic', 'profile_path': None}, {'credit_id': '589216d79251412dc8009aa0', 'department': 'Sound', 'gender': 0, 'id': 8067, 'job': 'Assistant Sound Editor', 'name': 'Dan Engstrom', 'profile_path': None}, {'credit_id': '589216e49251412dcd009a4f', 'department': 'Production', 'gender': 1, 'id': 7902, 'job': 'Casting Consultant', 'name': 'Ruth Lambert', 'profile_path': None}, {'credit_id': '589216f39251412dc2009cf3', 'department': 'Production', 'gender': 0, 'id': 84493, 'job': 'ADR Voice Casting', 'name': 'Mickie McGowan', 'profile_path': '/k7TjJBfINsg8vLQxJwos6XObAD6.jpg'}]

In [39]:
credits_clean['cast_parsed'] = credits_clean['cast'].apply(parse_genres)
credits_clean['crew_parsed'] = credits_clean['crew'].apply(parse_genres)

In [40]:
def get_cast_names(cast_list):
    if not isinstance(cast_list, list):
        return []

    return [
        person['name']
        for person in cast_list[:5]
        if isinstance(person, dict) and person.get('name')
    ]

credits_clean['cast_names'] = credits_clean['cast_parsed'].apply(
    get_cast_names
)

In [41]:
def get_director(crew_list):
    if not isinstance(crew_list, list):
        return ''

    for person in crew_list:
        if (
            isinstance(person, dict)
            and person.get('job') == 'Director'
        ):
            return person.get('name', '')

    return ''

credits_clean['director'] = credits_clean['crew_parsed'].apply(
    get_director
)

In [42]:
credits_clean[['id', 'cast_names', 'director']].head()

      id                                         cast_names         director
0    862  [Tom Hanks, Tim Allen, Don Rickles, Jim Varney...    John Lasseter
1   8844  [Robin Williams, Jonathan Hyde, Kirsten Dunst,...     Joe Johnston
2  15602  [Walter Matthau, Jack Lemmon, Ann-Margret, Sop...    Howard Deutch
3  31357  [Whitney Houston, Angela Bassett, Loretta Devi...  Forest Whitaker
4  11862  [Steve Martin, Diane Keaton, Martin Short, Kim...    Charles Shyer

In [43]:
keywords_clean = keywords.copy()

In [44]:
keywords_clean.columns.tolist()

['id', 'keywords']

In [45]:
keywords_clean.head()

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

In [46]:
keywords_clean['keywords_parsed'] = keywords_clean['keywords'].apply(parse_genres)

In [47]:
def get_keyword_names(keyword_list):
    if not isinstance(keyword_list, list):
        return []

    return [
        keyword['name']
        for keyword in keyword_list
        if isinstance(keyword, dict) and keyword.get('name')
    ]

In [48]:
keywords_clean['keyword_names'] = keywords_clean['keywords_parsed'].apply(
    get_keyword_names
)

In [49]:
keywords_clean['keywords_text'] = keywords_clean['keyword_names'].apply(
    lambda x: ' '.join(x)
)

In [50]:
keywords_clean[['id', 'keywords', 'keywords_text']].head(10)

,id,keywords,keywords_text
0,862,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",jealousy toy boy friendship friends rivalry bo...
1,8844,"[{'id': 10090, 'name': 'board game'}, {'id': 1...",board game disappearance based on children's b...
2,15602,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392...",fishing best friend duringcreditsstinger old men
3,31357,"[{'id': 818, 'name': 'based on novel'}, {'id':...",based on novel interracial relationship single...
4,11862,"[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...",baby midlife crisis confidence aging daughter ...
5,949,"[{'id': 642, 'name': 'robbery'}, {'id': 703, '...",robbery detective bank obsession chase shootin...
6,11860,"[{'id': 90, 'name': 'paris'}, {'id': 380, 'nam...",paris brother brother relationship chauffeur l...
7,45325,[],
8,9091,"[{'id': 949, 'name': 'terrorist'}, {'id': 1562...",terrorist hostage explosive vice president
9,710,"[{'id': 701, 'name': 'cuba'}, {'id': 769, 'nam...",cuba falsely accused secret identity computer ...

In [51]:
movies_clean['id'].head()

0      862
1     8844
2    15602
3    31357
4    11862
Name: id, dtype: object

In [52]:
credits_clean['id'].head()

0      862
1     8844
2    15602
3    31357
4    11862
Name: id, dtype: int64

In [53]:
keywords_clean['id'].head()

0      862
1     8844
2    15602
3    31357
4    11862
Name: id, dtype: int64

In [54]:
ratings_clean = ratings.copy()

In [55]:
ratings_clean['movieId'].head()

0     110
1     147
2     858
3    1221
4    1246
Name: movieId, dtype: int64

In [56]:
print("movies:", movies_clean['id'].dtype)
print("credits:", credits_clean['id'].dtype)
print("keywords:", keywords_clean['id'].dtype)
print("ratings:", ratings_clean['movieId'].dtype)

movies: object
credits: int64
keywords: int64
ratings: int64

In [57]:
movies_clean['id'] = pd.to_numeric(
    movies_clean['id'],
    errors='coerce'
)

In [58]:
movies_clean['id'].isna().sum()

np.int64(0)

In [59]:
movies_clean['id'] = movies_clean['id'].astype(int)

In [60]:
print("movies:", movies_clean['id'].dtype)
print("credits:", credits_clean['id'].dtype)
print("keywords:", keywords_clean['id'].dtype)
print("ratings:", ratings_clean['movieId'].dtype)

movies: int64
credits: int64
keywords: int64
ratings: int64

In [61]:
print("Movies:", movies_clean['id'].nunique())
print("Credits:", credits_clean['id'].nunique())
print("Keywords:", keywords_clean['id'].nunique())
print("Ratings:", ratings_clean['movieId'].nunique())

Movies: 45430
Credits: 45432
Keywords: 45432
Ratings: 45115

In [62]:
len(set(movies_clean['id']) & set(credits_clean['id']))

45429

In [63]:
len(set(movies_clean['id']) & set(keywords_clean['id']))

45429

In [64]:
len(set(movies_clean['id']) & set(ratings_clean['movieId']))

7565

In [65]:
credits_use = credits_clean[['id', 'cast_names', 'director']].copy()

In [66]:
keywords_use = keywords_clean[['id', 'keywords_text']].copy()

In [67]:
movies_model = movies_clean.merge(
    credits_use,
    on='id',
    how='left'
)

In [68]:
movies_model = movies_model.merge(
    keywords_use,
    on='id',
    how='left'
)

In [69]:
movies_model[
    ['id', 'title', 'genres_text', 'overview',
     'cast_names', 'director', 'keywords_text']
].head()

,id,title,genres_text,overview,cast_names,director,keywords_text
0,862,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...","[Tom Hanks, Tim Allen, Don Rickles, Jim Varney...",John Lasseter,jealousy toy boy friendship friends rivalry bo...
1,8844,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,"[Robin Williams, Jonathan Hyde, Kirsten Dunst,...",Joe Johnston,board game disappearance based on children's b...
2,15602,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,"[Walter Matthau, Jack Lemmon, Ann-Margret, Sop...",Howard Deutch,fishing best friend duringcreditsstinger old men
3,31357,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...","[Whitney Houston, Angela Bassett, Loretta Devi...",Forest Whitaker,based on novel interracial relationship single...
4,11862,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,"[Steve Martin, Diane Keaton, Martin Short, Kim...",Charles Shyer,baby midlife crisis confidence aging daughter ...

In [70]:
movies_model[
    ['id', 'title', 'genres_text', 'overview',
     'cast_names', 'director', 'keywords_text']
].head()

,id,title,genres_text,overview,cast_names,director,keywords_text
0,862,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...","[Tom Hanks, Tim Allen, Don Rickles, Jim Varney...",John Lasseter,jealousy toy boy friendship friends rivalry bo...
1,8844,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,"[Robin Williams, Jonathan Hyde, Kirsten Dunst,...",Joe Johnston,board game disappearance based on children's b...
2,15602,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,"[Walter Matthau, Jack Lemmon, Ann-Margret, Sop...",Howard Deutch,fishing best friend duringcreditsstinger old men
3,31357,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...","[Whitney Houston, Angela Bassett, Loretta Devi...",Forest Whitaker,based on novel interracial relationship single...
4,11862,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,"[Steve Martin, Diane Keaton, Martin Short, Kim...",Charles Shyer,baby midlife crisis confidence aging daughter ...

In [71]:
movies_model['overview'] = movies_model['overview'].fillna('')
movies_model['keywords_text'] = movies_model['keywords_text'].fillna('')
movies_model['director'] = movies_model['director'].fillna('')

In [72]:
movies_model['cast_text'] = movies_model['cast_names'].apply(
    lambda x: ' '.join(x) if isinstance(x, list) else ''
)

In [73]:
movies_model['tags'] = (
    movies_model['genres_text'] + ' ' +
    movies_model['overview'] + ' ' +
    movies_model['keywords_text'] + ' ' +
    movies_model['cast_text'] + ' ' +
    movies_model['director']
)

In [74]:
movies_model[['title', 'tags']].head()

,title,tags
0,Toy Story,"Animation Comedy Family Led by Woody, Andy's t..."
1,Jumanji,Adventure Fantasy Family When siblings Judy an...
2,Grumpier Old Men,Romance Comedy A family wedding reignites the ...
3,Waiting to Exhale,"Comedy Drama Romance Cheated on, mistreated an..."
4,Father of the Bride Part II,Comedy Just when George Banks has recovered fr...

In [77]:
movies_model['tags'] = movies_model['tags'].str.lower()

In [76]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [78]:
tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=50000
)

In [79]:
tfidf_matrix = tfidf.fit_transform(movies_model['tags'])

In [80]:
tfidf_matrix.shape

(46625, 50000)

In [87]:
movie_indices = pd.Series(
    movies_model.index,
    index=movies_model['title']
)

movie_indices = movie_indices[~movie_indices.index.duplicated(keep='first')]

In [82]:
def recommend_movies(title, n=10):

    if title not in movie_indices:
        return "Movie not found"

    idx = movie_indices[title]

    scores = cosine_similarity(
        tfidf_matrix[idx],
        tfidf_matrix
    ).flatten()

    top_indices = scores.argsort()[-n-1:][::-1]

    top_indices = [
        i for i in top_indices
        if i != idx
    ][:n]

    return movies_model.iloc[top_indices][
        ['title', 'vote_average', 'genres_text']
    ]

In [83]:
recommend_movies("Toy Story", 10)

,title,vote_average,genres_text
3012,Toy Story 2,7.3,Animation Comedy Family
15444,Toy Story 3,7.6,Animation Family Comedy
25950,Toy Story That Time Forgot,6.8,Animation Family
25848,"Silent Night, Deadly Night 5: The Toy Maker",5.1,Horror Science Fiction
1823,Small Soldiers,6.2,Comedy Adventure Fantasy Science Fiction Action
24670,Small Fry,6.8,Animation Family
22063,Toy Story of Terror!,7.3,Animation Comedy Family
37871,Toy Reanimator,0.0,Science Fiction Fantasy
25948,Partysaurus Rex,7.4,Animation Comedy Family Fantasy
2154,Toys,5.0,Fantasy Comedy Science Fiction

In [88]:
recommend_movies("The Dark Knight", 10)

,title,vote_average,genres_text
18368,The Dark Knight Rises,7.6,Action Crime Drama Thriller
10170,Batman Begins,7.5,Action Crime Drama
1337,Batman Returns,6.6,Action Fantasy
15607,Batman: Under the Red Hood,7.6,Action Animation
150,Batman Forever,5.2,Action Crime Fantasy
585,Batman,7.0,Fantasy Action
21326,Batman Unmasked: The Psychology of the Dark Kn...,8.0,Documentary
20352,"Batman: The Dark Knight Returns, Part 2",7.9,Action Animation
43126,The Lego Batman Movie,7.2,Action Animation Comedy Family Fantasy
43132,Batman Beyond Darwyn Cooke's Batman 75th Anniv...,7.7,Action Animation Science Fiction

In [89]:
recommend_movies("Titanic", 10)

,title,vote_average,genres_text
3301,A Night to Remember,7.5,Drama Action History
4755,Titanica,6.0,Documentary
3300,Titanic,6.2,Drama Action Romance
26246,Carry On Cruising,5.7,Comedy
45433,Titanic: The Final Word with James Cameron,6.6,Documentary History
4730,Death Ship,5.5,Adventure Horror Mystery Thriller
25623,Titanic,6.3,Action Drama Romance
6184,Ghosts of the Abyss,7.1,Documentary
2436,Beyond the Poseidon Adventure,5.3,Action Adventure Drama
34961,Doctor Who: Voyage of the Damned,8.0,Science Fiction

In [90]:
ratings_clean.head()

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [91]:
ratings_clean.shape

(26024289, 4)

In [92]:
ratings_clean[['userId', 'movieId', 'rating']].head()

   userId  movieId  rating
0       1      110     1.0
1       1      147     4.5
2       1      858     5.0
3       1     1221     5.0
4       1     1246     5.0

In [93]:
print("Shape:", ratings_clean.shape)
print("Unique users:", ratings_clean['userId'].nunique())
print("Unique movies:", ratings_clean['movieId'].nunique())
print("Total ratings:", len(ratings_clean))

Shape: (26024289, 4)
Unique users: 270896
Unique movies: 45115
Total ratings: 26024289

In [94]:
ratings_model = ratings_clean[
    ratings_clean['movieId'].isin(movies_model['id'])
].copy()

print("Ratings after filtering:", ratings_model.shape)
print("Users:", ratings_model['userId'].nunique())
print("Movies:", ratings_model['movieId'].nunique())

Ratings after filtering: (11436568, 4)
Users: 265917
Movies: 7565

In [95]:
from scipy.sparse import csr_matrix

user_ids = ratings_model['userId'].unique()
movie_ids = ratings_model['movieId'].unique()

user_to_idx = {user_id: i for i, user_id in enumerate(user_ids)}
movie_to_idx = {movie_id: i for i, movie_id in enumerate(movie_ids)}

print("Users:", len(user_to_idx))
print("Movies:", len(movie_to_idx))

Users: 265917
Movies: 7565

In [96]:
rows = ratings_model['userId'].map(user_to_idx)
cols = ratings_model['movieId'].map(movie_to_idx)

user_item_matrix = csr_matrix(
    (
        ratings_model['rating'].values,
        (rows, cols)
    ),
    shape=(len(user_ids), len(movie_ids))
)

print("Matrix shape:", user_item_matrix.shape)
print("Stored ratings:", user_item_matrix.nnz)

Matrix shape: (265917, 7565)
Stored ratings: 11436568

In [97]:
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(
    n_components=50,
    random_state=42
)

user_factors = svd.fit_transform(user_item_matrix)

print("Training complete!")
print("User factors shape:", user_factors.shape)

Training complete!
User factors shape: (265917, 50)

In [98]:
movie_factors = svd.components_.T

print("Movie factors shape:", movie_factors.shape)

Movie factors shape: (7565, 50)

In [99]:
def recommend_collaborative(user_id, n=10):

    # Check whether user exists
    if user_id not in user_to_idx:
        return "User not found"

    # Get user's learned preference vector
    user_index = user_to_idx[user_id]
    user_vector = user_factors[user_index]

    # Compare user preferences with every movie
    scores = movie_factors @ user_vector

    # Get highest-scoring movies
    top_indices = scores.argsort()[::-1]

    # Movies already rated by this user
    rated_movies = set(
        ratings_model[
            ratings_model['userId'] == user_id
        ]['movieId']
    )

    recommendations = []

    for idx in top_indices:

        movie_id = movie_ids[idx]

        # Don't recommend movies the user already rated
        if movie_id not in rated_movies:
            recommendations.append(movie_id)

        if len(recommendations) == n:
            break

    # Convert movie IDs to movie information
    result = movies_model[
        movies_model['id'].isin(recommendations)
    ][['id', 'title', 'vote_average', 'genres_text']].copy()

    # Keep recommendation order
    order = {movie_id: i for i, movie_id in enumerate(recommendations)}

    result['order'] = result['id'].map(order)

    result = result.sort_values('order')

    return result.drop(columns='order')

In [100]:
recommend_collaborative(1, 10)

,id,title,vote_average,genres_text
44518,48780,Boat,7.6,Foreign
2664,912,The Thomas Crown Affair,6.9,Romance Crime Thriller Drama
13494,1961,My Name Is Bruce,5.9,Comedy Horror
11538,1259,Notes on a Scandal,6.9,Drama Romance
3074,1213,The Talented Mr. Ripley,7.1,Thriller Crime Drama
4163,4973,Under the Sand,6.4,Drama Mystery
28203,44191,Loose Screws,5.3,Comedy
29321,46578,Cheerleaders' Wild Weekend,2.7,Comedy Crime
5525,1682,Mothra vs. Godzilla,6.4,Fantasy Science Fiction Action Adventure
30456,74458,Mere Brother Ki Dulhan,6.5,Drama Comedy Romance

In [101]:
recommend_movies("The Dark Knight")

,title,vote_average,genres_text
18368,The Dark Knight Rises,7.6,Action Crime Drama Thriller
10170,Batman Begins,7.5,Action Crime Drama
1337,Batman Returns,6.6,Action Fantasy
15607,Batman: Under the Red Hood,7.6,Action Animation
150,Batman Forever,5.2,Action Crime Fantasy
585,Batman,7.0,Fantasy Action
21326,Batman Unmasked: The Psychology of the Dark Kn...,8.0,Documentary
20352,"Batman: The Dark Knight Returns, Part 2",7.9,Action Animation
43126,The Lego Batman Movie,7.2,Action Animation Comedy Family Fantasy
43132,Batman Beyond Darwyn Cooke's Batman 75th Anniv...,7.7,Action Animation Science Fiction

In [102]:
recommend_collaborative(1, 10)

,id,title,vote_average,genres_text
44518,48780,Boat,7.6,Foreign
2664,912,The Thomas Crown Affair,6.9,Romance Crime Thriller Drama
13494,1961,My Name Is Bruce,5.9,Comedy Horror
11538,1259,Notes on a Scandal,6.9,Drama Romance
3074,1213,The Talented Mr. Ripley,7.1,Thriller Crime Drama
4163,4973,Under the Sand,6.4,Drama Mystery
28203,44191,Loose Screws,5.3,Comedy
29321,46578,Cheerleaders' Wild Weekend,2.7,Comedy Crime
5525,1682,Mothra vs. Godzilla,6.4,Fantasy Science Fiction Action Adventure
30456,74458,Mere Brother Ki Dulhan,6.5,Drama Comedy Romance

In [103]:
movie_rating_counts = ratings_model['movieId'].value_counts()

print(movie_rating_counts.describe())
print("\nRatings for top 10 most-rated movies:")
print(movie_rating_counts.head(10))

count     7565.000000
mean      1511.773695
std       5305.245799
min          1.000000
25%          7.000000
50%         45.000000
75%        469.000000
max      91082.000000
Name: count, dtype: float64

Ratings for top 10 most-rated movies:
movieId
318     91082
296     87901
593     84078
260     77045
480     74355
527     67662
110     66512
2959    60024
150     57416
780     57232
Name: count, dtype: int64

In [104]:
# Movies with at least 50 ratings
popular_movies = set(
    movie_rating_counts[movie_rating_counts >= 50].index
)

def recommend_collaborative(user_id, n=10):

    if user_id not in user_to_idx:
        return "User not found"

    user_index = user_to_idx[user_id]
    user_vector = user_factors[user_index]

    scores = movie_factors @ user_vector
    top_indices = scores.argsort()[::-1]

    rated_movies = set(
        ratings_model[
            ratings_model['userId'] == user_id
        ]['movieId']
    )

    recommendations = []

    for idx in top_indices:

        movie_id = movie_ids[idx]

        if movie_id in popular_movies and movie_id not in rated_movies:
            recommendations.append(movie_id)

        if len(recommendations) == n:
            break

    result = movies_model[
        movies_model['id'].isin(recommendations)
    ][['id', 'title', 'vote_average', 'genres_text']].copy()

    order = {
        movie_id: i
        for i, movie_id in enumerate(recommendations)
    }

    result['order'] = result['id'].map(order)

    return result.sort_values('order').drop(columns='order')

In [105]:
recommend_collaborative(1, 10)

,id,title,vote_average,genres_text
44518,48780,Boat,7.6,Foreign
2664,912,The Thomas Crown Affair,6.9,Romance Crime Thriller Drama
13494,1961,My Name Is Bruce,5.9,Comedy Horror
11538,1259,Notes on a Scandal,6.9,Drama Romance
3074,1213,The Talented Mr. Ripley,7.1,Thriller Crime Drama
4163,4973,Under the Sand,6.4,Drama Mystery
28203,44191,Loose Screws,5.3,Comedy
29321,46578,Cheerleaders' Wild Weekend,2.7,Comedy Crime
5525,1682,Mothra vs. Godzilla,6.4,Fantasy Science Fiction Action Adventure
30456,74458,Mere Brother Ki Dulhan,6.5,Drama Comedy Romance

In [107]:
def hybrid_recommend(movie_title, user_id, n=10):

    # ---------- CONTENT SCORE ----------
    if movie_title not in movie_indices:
        return "Movie not found"

    if user_id not in user_to_idx:
        return "User not found"

    movie_idx = movie_indices[movie_title]

    content_scores = cosine_similarity(
        tfidf_matrix[movie_idx],
        tfidf_matrix
    ).flatten()

    # ---------- COLLABORATIVE SCORE ----------
    user_idx = user_to_idx[user_id]
    user_vector = user_factors[user_idx]

    collaborative_scores = movie_factors @ user_vector

    # ---------- NORMALIZE SCORES ----------
    content_scores = (
        content_scores - content_scores.min()
    ) / (
        content_scores.max() - content_scores.min()
    )

    collaborative_scores = (
        collaborative_scores - collaborative_scores.min()
    ) / (
        collaborative_scores.max() - collaborative_scores.min()
    )

    # ---------- COMBINE ----------
    hybrid_scores = (
        0.6 * content_scores +
        0.4 * collaborative_scores
    )

    # ---------- REMOVE ORIGINAL MOVIE ----------
    hybrid_scores[movie_idx] = -1

    # ---------- TOP MOVIES ----------
    top_indices = hybrid_scores.argsort()[::-1]

    rated_movies = set(
        ratings_model[
            ratings_model['userId'] == user_id
        ]['movieId']
    )

    recommendations = []

    for idx in top_indices:

        movie_id = movie_ids[idx] if idx < len(movie_ids) else None

        if movie_id is not None and movie_id not in rated_movies:
            recommendations.append(idx)

        if len(recommendations) == n:
            break

    return movies_model.iloc[recommendations][
        ['title', 'vote_average', 'genres_text']
    ]

In [108]:
# Map movie ID -> collaborative movie index
collab_movie_to_idx = {
    movie_id: i
    for i, movie_id in enumerate(movie_ids)
}

# For every movie in movies_model, store its collaborative index
movies_model['collab_idx'] = movies_model['id'].map(
    collab_movie_to_idx
)

print("Movies with collaborative data:",
      movies_model['collab_idx'].notna().sum())

Movies with collaborative data: 7697

In [109]:
def hybrid_recommend(movie_title, user_id, n=10):

    if movie_title not in movie_indices:
        return "Movie not found"

    if user_id not in user_to_idx:
        return "User not found"

    # Content score
    movie_idx = movie_indices[movie_title]

    content_scores = cosine_similarity(
        tfidf_matrix[movie_idx],
        tfidf_matrix
    ).flatten()

    # Collaborative score
    user_idx = user_to_idx[user_id]
    user_vector = user_factors[user_idx]

    collab_scores = movie_factors @ user_vector

    # Create full-length collaborative score
    full_collab_scores = np.zeros(len(movies_model))

    for i, collab_idx in enumerate(movies_model['collab_idx']):
        if pd.notna(collab_idx):
            full_collab_scores[i] = collab_scores[int(collab_idx)]

    # Normalize both scores
    content_scores = (
        content_scores - content_scores.min()
    ) / (
        content_scores.max() - content_scores.min()
    )

    full_collab_scores = (
        full_collab_scores - full_collab_scores.min()
    ) / (
        full_collab_scores.max() - full_collab_scores.min()
    )

    # Hybrid score
    hybrid_scores = (
        0.6 * content_scores +
        0.4 * full_collab_scores
    )

    # Don't recommend the movie itself
    hybrid_scores[movie_idx] = -1

    # Movies already rated by user
    rated_movies = set(
        ratings_model[
            ratings_model['userId'] == user_id
        ]['movieId']
    )

    # Rank
    top_indices = hybrid_scores.argsort()[::-1]

    recommendations = []

    for idx in top_indices:

        movie_id = movies_model.iloc[idx]['id']

        if movie_id not in rated_movies:
            recommendations.append(idx)

        if len(recommendations) == n:
            break

    return movies_model.iloc[recommendations][
        ['id', 'title', 'vote_average', 'genres_text']
    ]

In [110]:
hybrid_recommend("The Dark Knight", 1, 10)

,id,title,vote_average,genres_text
18368,49026,The Dark Knight Rises,7.6,Action Crime Drama Thriller
10170,272,Batman Begins,7.5,Action Crime Drama
1337,364,Batman Returns,6.6,Action Fantasy
15607,40662,Batman: Under the Red Hood,7.6,Action Animation
150,414,Batman Forever,5.2,Action Crime Fantasy
585,268,Batman,7.0,Fantasy Action
21326,29751,Batman Unmasked: The Psychology of the Dark Kn...,8.0,Documentary
20352,142061,"Batman: The Dark Knight Returns, Part 2",7.9,Action Animation
43126,324849,The Lego Batman Movie,7.2,Action Animation Comedy Family Fantasy
43132,269246,Batman Beyond Darwyn Cooke's Batman 75th Anniv...,7.7,Action Animation Science Fiction

In [111]:
from sklearn.model_selection import train_test_split

ratings_eval = ratings_model.sample(
    n=100000,
    random_state=42
)

train_eval, test_eval = train_test_split(
    ratings_eval,
    test_size=0.2,
    random_state=42
)

print("Training ratings:", len(train_eval))
print("Testing ratings:", len(test_eval))

Training ratings: 80000
Testing ratings: 20000

In [112]:
from sklearn.metrics import mean_squared_error
import numpy as np

global_mean = train_eval['rating'].mean()

baseline_predictions = np.full(
    len(test_eval),
    global_mean
)

baseline_rmse = np.sqrt(
    mean_squared_error(
        test_eval['rating'],
        baseline_predictions
    )
)

print("Baseline RMSE:", baseline_rmse)

Baseline RMSE: 1.075749406518544

In [113]:
from scipy.sparse import csr_matrix
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics import mean_squared_error
import numpy as np

# Create mappings from the evaluation training data
eval_user_ids = train_eval['userId'].unique()
eval_movie_ids = train_eval['movieId'].unique()

eval_user_to_idx = {
    user_id: i
    for i, user_id in enumerate(eval_user_ids)
}

eval_movie_to_idx = {
    movie_id: i
    for i, movie_id in enumerate(eval_movie_ids)
}

# Convert training ratings to sparse matrix
train_rows = train_eval['userId'].map(eval_user_to_idx)
train_cols = train_eval['movieId'].map(eval_movie_to_idx)

eval_matrix = csr_matrix(
    (
        train_eval['rating'].values,
        (train_rows, train_cols)
    ),
    shape=(
        len(eval_user_ids),
        len(eval_movie_ids)
    )
)

# Train SVD
eval_svd = TruncatedSVD(
    n_components=20,
    random_state=42
)

eval_user_factors = eval_svd.fit_transform(eval_matrix)
eval_movie_factors = eval_svd.components_.T

print("Evaluation model trained!")
print("Users:", len(eval_user_ids))
print("Movies:", len(eval_movie_ids))

Evaluation model trained!
Users: 52890
Movies: 3306

In [114]:
predictions = []
actual = []

for _, row in test_eval.iterrows():

    user_id = row['userId']
    movie_id = row['movieId']

    # Only evaluate users/movies seen during training
    if (
        user_id in eval_user_to_idx
        and movie_id in eval_movie_to_idx
    ):

        user_idx = eval_user_to_idx[user_id]
        movie_idx = eval_movie_to_idx[movie_id]

        prediction = (
            eval_user_factors[user_idx]
            @ eval_movie_factors[movie_idx]
        )

        predictions.append(prediction)
        actual.append(row['rating'])

model_rmse = np.sqrt(
    mean_squared_error(actual, predictions)
)

print("SVD RMSE:", model_rmse)
print("Test ratings evaluated:", len(actual))

SVD RMSE: 3.6059129412233215
Test ratings evaluated: 10420

In [115]:
import joblib

joblib.dump(tfidf, 'tfidf_vectorizer.pkl')
joblib.dump(tfidf_matrix, 'tfidf_matrix.pkl')
joblib.dump(movie_indices, 'movie_indices.pkl')

joblib.dump(svd, 'svd_model.pkl')
joblib.dump(user_to_idx, 'user_to_idx.pkl')
joblib.dump(movie_to_idx, 'movie_to_idx.pkl')
joblib.dump(user_factors, 'user_factors.pkl')
joblib.dump(movie_factors, 'movie_factors.pkl')

movies_model.to_pickle('movies_model.pkl')

print("All models saved successfully!")

All models saved successfully!

In [116]:
!pip install -q gradio

In [117]:
import gradio as gr

def movie_recommender_ui(movie_title, user_id):

    try:
        user_id = int(user_id)
    except:
        return "Please enter a valid User ID."

    result = hybrid_recommend(
        movie_title,
        user_id,
        n=10
    )

    if isinstance(result, str):
        return result

    output = ""

    for i, row in result.reset_index(drop=True).iterrows():
        output += (
            f"{i+1}. {row['title']}  "
            f"(Rating: {row['vote_average']})\n"
            f"   Genres: {row['genres_text']}\n\n"
        )

    return output


demo = gr.Interface(
    fn=movie_recommender_ui,
    inputs=[
        gr.Textbox(
            label="Movie",
            placeholder="Enter a movie title"
        ),
        gr.Number(
            label="User ID",
            value=1
        )
    ],
    outputs=gr.Textbox(
        label="Recommended Movies"
    ),
    title="🎬 Movie Recommendation System",
    description="Hybrid recommender using Content-Based Filtering + Collaborative Filtering"
)

demo.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://5a3d5ef91539380e0a.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)